
jenkins:
  build: .
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
  ports:
   - "8080:8080"
  links:
   - xld
   - socat
  environment:
   - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
   - jenkins_password=admin
   - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
   - dockerhubpass=$DOCKER_HUB_PASS
   - dockerhubuser=$DOCKER_HUB_USER

xld:
  image: xebialabs/xl-deploy:10.0.0
  links:
   - socat
  ports:
   - "4516:4516"
  environment:
   - ACCEPT_EULA=Y
   - ADMIN_PASSWORD=admin

xlr:
  image: xebialabs/xl-release:10.0.0
  links:
   - jenkins
   - xld
   - socat
  ports:
   - "5516:5516"
  environment:
   - ACCEPT_EULA=Y
   - ADMIN_PASSWORD=admin

socat:
  image: bobrik/socat
  ports:
    - "2376:2375"
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CLIENT:/var/run/docker.sock
