---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/container-demo/%BUILD_NUMBER%
  type: udm.DeploymentPackage
  deployables:
  - name: mysql
    type: k8s.ResourcesFile
    createOrder: "61"
    file: !file "artifacts/mysql.yaml"
    tags:
    - gke
  - name: app
    type: k8s.ResourcesFile
    createOrder: "62"
    file: !file "artifacts/app.yaml"
    tags:
    - gke
    - local
  - name: ingress
    type: k8s.ResourcesFile
    createOrder: "63"
    file: !file "artifacts/ingress.yaml"
    tags:
    - gke
    - local
  - name: sql_config
    type: k8s.ResourcesFile
    file: !file "artifacts/configmap.yaml"
    tags:
    - gke
  - name: secrets
    type: k8s.ResourcesFile
    file: !file "artifacts/secret.yaml"
    tags:
    - gke
  - name: local_petclinic_ns
    type: k8s.NamespaceSpec
    namespaceName: petclinic
    tags:
    - local
  - name: gke_petclinic_ns
    type: k8s.NamespaceSpec
    namespaceName: petclinic
    tags:
    - gke
